spring.application.name=Loan Approval Process

# Andmebaasi seaded (port 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/loan_db
spring.datasource.username=user
spring.datasource.password=Siemann

# Flyway seaded
spring.flyway.enabled=true

# Hibernate seaded
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

loan.validation.max-age=70