spring.application.name=Loan Approval Process

# Andmebaasi seaded
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/loan_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Siemann}

# Flyway seaded
spring.flyway.enabled=true

# Hibernate seaded
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html